### ISSUE TITLE
FB給店家的罐頭簡訊

### ISSUE THREAD

**Issue by dolcechen** [Intention30/Uber-X-OnlineStore#13]
您好，我是Fanshop的小工，最近因為有不少網拍賣家利用uber的服務來運送商品，已取得更快速的交貨時間，因此我們想提供這樣的平台讓店家與uber司機可以合作，在此做個市場調查，煩請您花一分鐘撥空填寫以下問卷。http://bit.ly/fanshopxuber 謝謝

**Comment by shockhuang** [comment]
您好，我是Fanshop的網拍小幫手，
已經有不少網拍賣家利用 uber 服務來配送商品，
真的大大地提高交貨速度，
然而使用 uber 本身的服務費用很高，
因此我們想提供平台讓店家與 uber 司機合作，
想詢問您是否願意以 $60 元的價格使用 uber 的當日配送服務，
以下是我們的報名表格，目前台中商圈提供 100 個店家加入我們，
如果有興趣，請不要錯過報名喔，謝謝！

http://bit.ly/fanshopxuber

**Comment by shockhuang** [comment]
已轉移到 wiki
